#!/usr/bin/env bash

set -e

: "${USER:=onur}"
: "${PASSWORD:=z}"
: "${HOST:=127.0.0.1}"
: "${PORT:=5984}"
: "${PROTOCOL:=http}"
: "${BIN:=./bin.js}"
: "${NAME:=example}"
: "${DOC:=fun}"

URL="$PROTOCOL://$USER:$PASSWORD@$HOST:$PORT/$NAME"

DOCURL="$URL/_design/$DOC"

publish () {
    rev=$(curl -s -X GET "$1" | jq '._rev')

    if [[ "$rev" == "null" ]]; then
        data=$({ echo -n "{\"_id\": \"_design/$DOC\",\"language\": \"javascript\"}"; $BIN "designs/$DOC"; } | jq -c -s add)
    else
        data=$({ echo -n "{\"_id\": \"_design/$DOC\",\"language\": \"javascript\",\"_rev\": $rev}"; $BIN "designs/$DOC"; } | jq -c -s add)
    fi

    curl -s -X PUT "$DOCURL" -d "$data" -H "Content-Type: application/json"
}

publish "$DOCURL"
